services:
  transaktionsanalyse:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: ${DATABASE_URL}
    networks:
      - postgres-network
    environment:
      ORIGIN: ${ORIGIN}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      AUTH0_SECRET: ${AUTH0_SECRET}
      AUTH0_CID: ${AUTH0_CID}
      AUTH0_CSECRET: ${AUTH0_CSECRET}
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - 5173:3000
    depends_on:
      - database
    restart: unless-stopped
 
  database:
    image: 'postgres:latest'
    networks:
      - postgres-network
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: unless-stopped
    user: 1000:1000

networks: 
  postgres-network:
    driver: bridge
